server:
  error:
    include-message: always

spring:
 h2:
  console:
   enabled: true
   path: /h2
   
 datasource:
  url: jdbc:h2:mem:api_db
  username: sa
  password:
  driverClassName: org.h2.Driver
  
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  properties.hibernate.show_sql: true
  properties.hibernate.format_sql: true

# mvc:
#  pathmatch:
#   matching-strategy: ANT_PATH_MATCHER

#springfox:
#  documentation:
#    swagger-ui:
#      baseUrl: scheduler-service
  

   
  
  
